spring.application.name=blackhorse-erp

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

blackhorse.s3.region=${S3_REGION}
blackhorse.s3.endpoint=${S3_ENDPOINT}
blackhorse.s3.access-key=${S3_ACCESS_KEY_ID}
blackhorse.s3.secret-key=${S3_SECRET_ACCESS_KEY}
blackhorse.s3.bucket-name=${S3_BUCKET_NAME}
blackhorse.s3.public-url=${S3_PUBLIC_URL:}

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-part-count=250

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=false

spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.default-property-inclusion=non_null

spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never

blackhorse.security.jwt.secret=${JWT_SECRET:CyjzHS556esJuhcaf8H26OprCrcubj78f6a0bg7sg5c8d2e}
blackhorse.security.jwt.access-token-ttl=${JWT_ACCESS_TTL:14d}

blackhorse.seed.admin.enabled=${SEED_ADMIN_ENABLED:true}
blackhorse.seed.admin.fullname=${SEED_ADMIN_NAME}
blackhorse.seed.admin.phone=${SEED_ADMIN_PHONE}
blackhorse.seed.admin.password=${SEED_ADMIN_PASSWORD}
blackhorse.seed.admin.email=${SEED_ADMIN_EMAIL}
